version: '3'

volumes:
  postgres_volume:

services:
  postgresql:
    image: postgres:14
    environment:
      - "POSTGRES_DB=${PG_DATABASE}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data